# Generated by Django 4.1.3 on 2022-11-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('stock', models.PositiveIntegerField(verbose_name='stock')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
                ('category', models.CharField(choices=[('other', 'other'), ('pharmacy', 'pharmacy'), ('food', 'food')], default='other', max_length=20, verbose_name='category')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='description')),
            ],
        ),
    ]
