# Generated by Django 4.1.3 on 2023-01-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_order_orderproduct_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.PositiveIntegerField(default=0, verbose_name='количество'),
        ),
    ]
