# Generated by Django 4.1.3 on 2023-01-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_cart_quantity_cart_qty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
