# Generated by Django 4.1.3 on 2023-01-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
